### ISSUE TITLE
How can I get the result in paper?

### ISSUE THREAD

**Issue by hjw-0909** [mecarill/2pcnet#10]
I just get this result

![image](https://github.com/mecarill/2pcnet/assets/56182057/06ec3211-1c30-42f6-92ce-7d1af20773cb)

But I don't know how to get the result as shown below

<img width="1187" alt="image" src="https://github.com/mecarill/2pcnet/assets/56182057/9a9c8221-f57b-4661-bdda-83543357f6ea">

**Comment by cha-suyeon** [comment]
Did you get a score of 46.4 when training the model with the pre-trained weight pth?
